Create Class Videos Table
ctc-uci/cse pull request #16
Opened 2024-11-23 02:10 UTC by Priyansh4444

## Description
Creating class videos table following the constraints on the schema

## Screenshots/Media
![image](https://github.com/user-attachments/assets/5d16d82c-6ae1-46bf-a5e7-b5c6558e17f7)

## Issues
Closes #11

2024-12-02 20:07 UTC, h0ethan04 requested changes

2024-12-02 20:07 UTC, h0ethan04 commented on server/db/schema/class_videos.sql
> +  FOREIGN KEY (class_id) REFERENCES classes(id)
Whenever we use foreign keys we want to cascade on delete so that we don't leave junk in our database, can you add that?

2024-12-06 04:30 UTC, stevem-zhou approved these changes

2024-12-06 05:36 UTC, h0ethan04 approved these changes

2024-12-06 05:38 UTC, merged