finished
ctc-uci/cse pull request #17
Opened 2024-11-23 02:18 UTC by bowenwang0815

## Description

## Screenshots/Media

## Issues
Closes #

2024-11-23 06:01 UTC, bowenwang0815 commented
Create Student Table and Teacher Table

2024-12-04 06:09 UTC, stevem-zhou commented on server/db/schema/students.sql
> +  );
Could we add a foreign key constraint for the id here that references from the user table. 
The arrows from the [database model](https://www.figma.com/board/n2WrXKm7kz13meVmRrwwEe/%5BCSE%5D-1C.-Database-Model?t=nfUZyVNet3CXKCxR-0) shows where it needs to be referencing from.

2024-12-04 06:10 UTC, stevem-zhou commented on server/db/schema/teachers.sql
> + );
same as above.

2024-12-04 06:11 UTC, stevem-zhou commented
Could you guys also check out the cse-dev chat on slack and make sure that you guys have all the steps completed in this PR.

2024-12-04 06:51 UTC, bowenwang0815 commented on server/db/schema/students.sql
> +  );
hellow steven can you check new commit

2024-12-04 09:09 UTC, h0ethan04 requested changes

2024-12-04 09:09 UTC, h0ethan04 commented on server/db/schema/students.sql
> +    level ENUM('beginner', 'intermediate', 'advanced') NOT NULL,
Can you roll this back to when you had LEVEL as a type instead of an inline enum?

2024-12-04 09:09 UTC, h0ethan04 commented on server/db/schema/students.sql
> +    CONSTRAINT fk_user_student FOREIGN KEY (id) REFERENCES User (id)
In general whenever we use foreign keys we should be cascading on delete, can you add that?

2024-12-04 09:09 UTC, h0ethan04 commented on server/db/schema/teachers.sql
> +    CONSTRAINT fk_user_teacher FOREIGN KEY (id) REFERENCES User (id)
Same as the other table, can you add the cascading on delete?

2024-12-06 04:20 UTC, stevem-zhou commented on server/db/schema/students.sql
> +  );
lgtm!

2024-12-06 04:27 UTC, stevem-zhou approved these changes

2024-12-06 05:35 UTC, h0ethan04 approved these changes

2024-12-06 05:38 UTC, merged