Create Events Table
ctc-uci/cse pull request #22
Opened 2024-11-25 20:37 UTC by angeliinawang

Completed Issue #7

2024-11-25 20:42 UTC, angeliinawang commented
Screenshot of successful insert of rows into Events table
![InsertiontoEvents](https://github.com/user-attachments/assets/9366e5d9-40ee-4462-8cb3-16363ad35b12)

2024-12-04 06:01 UTC, stevem-zhou commented on server/db/schema/events.sql
> +    FOREIGN KEY (class_id) REFERENCES Classes(id),
We also want to include cascade on delete, in the event that the row that we are referencing gets deleted, then we can delete this row as well.

This is more of a NIT but you should also just list out all the columns first before adding in any constraints.

2024-12-04 06:04 UTC, stevem-zhou commented
Could you guys also check out the cse-dev chat on slack and make sure that you guys have all the steps completed in this PR.

2024-12-04 09:14 UTC, h0ethan04 requested changes

2024-12-04 09:14 UTC, h0ethan04 commented on server/db/schema/events.sql
> +DROP TYPE IF EXISTS level;
Can you change from `level` to `LEVEL` for the consistency with docs?

2024-12-04 09:14 UTC, h0ethan04 commented on server/db/schema/events.sql
> +-- );
Can you remove this from the pr?

2024-12-06 06:19 UTC, h0ethan04 approved these changes
lgtm!

2024-12-06 06:20 UTC, merged