Create event enrollments and articles tables
ctc-uci/cse pull request #23
Opened 2024-12-02 08:21 UTC by RaymondYan38

## Description
Wrote the events_enrollments and articles table.
## Screenshots/Media
<img width="1218" alt="Screenshot 2024-12-02 at 12 11 01 AM" src="https://github.com/user-attachments/assets/c9cc3632-7e19-40f1-89ad-0e470fa679bb">
<img width="1217" alt="Screenshot 2024-12-02 at 12 12 03 AM" src="https://github.com/user-attachments/assets/febe8984-92da-46db-9280-ed4dda9a0e31">

## Issues
Closes #9

2024-12-02 18:59 UTC, h0ethan04 requested changes

2024-12-02 18:59 UTC, h0ethan04 commented on server/db/schema/event_enrollments.sql
> +  FOREIGN KEY (student_id) REFERENCES students (id),
Whenever we use foreign keys we want to cascade on delete, can you add that?

2024-12-02 18:59 UTC, h0ethan04 commented on server/db/schema/event_enrollments.sql
> +  FOREIGN KEY (event_id) REFERENCES events (id)
same as student_id foreign key

2024-12-06 04:35 UTC, stevem-zhou approved these changes
lgtm

2024-12-06 05:34 UTC, h0ethan04 approved these changes

2024-12-06 05:39 UTC, merged