Create Articles and Event Enrollments CRUD Routes
ctc-uci/cse pull request #36
Opened 2024-12-27 02:43 UTC by Priyansh4444

## Description
Create Articles and Event Enrollments CRUD Routes in `articles.ts` and `event_enrollments.ts`

## Screenshots/Media
Postman Results:

### Articles

![image](https://github.com/user-attachments/assets/59fca392-b9ad-4eb4-bd77-1ad313b9ad28)
![image](https://github.com/user-attachments/assets/c55a39df-7467-4091-b290-f673799b6259)
![image](https://github.com/user-attachments/assets/fc9ba998-acf2-4f4d-ad94-c4abdcde4352)
![image](https://github.com/user-attachments/assets/b0ca4175-5b73-433e-8737-07c8f6297132)
![image](https://github.com/user-attachments/assets/1de85328-d4a1-4e26-9468-41363c3faec8)
![image](https://github.com/user-attachments/assets/b1107ad0-4a6e-4fad-9c10-8f26c0587f79)
![image](https://github.com/user-attachments/assets/f5cba1b6-5ac4-4d5a-aaca-60b43a0c8323)

### Event Enrollments
![image](https://github.com/user-attachments/assets/866b986c-bc45-4f05-8003-f38e0708fad5)

## Issues
Closes #32

2024-12-27 02:46 UTC, Priyansh4444 commented
I don't know how I would test the EventEnrollments page since we don't have the implementations of the students and events APIs / databases (which are required to post to the events page since the databases rely on foreign keys)

2024-12-27 02:50 UTC, h0ethan04 commented
> I don't know how I would test the EventEnrollments page since we don't have the implementations of the students and events APIs / databases (which are required to post to the events page since the databases rely on foreign keys)

You should have access to the prod db -- if you edit it and add a row for students and a row for events using a sql query you should be able to get the data from the neondb postgres instance and test using the remote instance.

2024-12-27 05:48 UTC, Arapaimace commented
Screenshots for event enrollments:
<img width="1320" alt="Screenshot 2024-12-26 at 9 43 01 PM" src="https://github.com/user-attachments/assets/f936430d-e6ac-47c4-92f9-d892b8cc6a23" />
<img width="1322" alt="Screenshot 2024-12-26 at 9 44 55 PM" src="https://github.com/user-attachments/assets/03907f10-956b-4c9f-8026-4542019c2578" />
<img width="1320" alt="Screenshot 2024-12-26 at 9 45 31 PM" src="https://github.com/user-attachments/assets/7eb7f75b-4ad6-405b-8052-4e906aa1f6be" />
<img width="1322" alt="Screenshot 2024-12-26 at 9 47 01 PM" src="https://github.com/user-attachments/assets/2e2f4bf8-7bcc-4994-9cc1-d5c722a195ed" />

2025-01-07 04:56 UTC, h0ethan04 requested changes

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/articles.ts
> +    res.json(keysToCamel(rows[0] as Article));
Can you set the status to 200 on success?

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/articles.ts
> +    res.json(keysToCamel(rows) as Article[]);
Can you set the status to 200 on success?

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/articles.ts
> +    res.json(keysToCamel(rows[0]) as Article);
Same as above, status 200

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/articles.ts
> +    res.json(keysToCamel(rows[0] as Article));
Status 200 on success

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/event_enrollments.ts
> +    res.json(keysToCamel(events) as EventEnrollment[]);
Set status 200 on success

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/event_enrollments.ts
> +    res.json(keysToCamel(events[0] as EventEnrollment));
Set status 200 on success

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/event_enrollments.ts
> +    res.json(keysToCamel(events[0]) as EventEnrollment);
Set status 200 on success

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/articles.ts
> +    );
We want to be able to update rows individually, can you do that? See [catalog.js](https://github.com/ctc-uci/aiss-backend/blob/dd6cd70521d990e7cbc027ca905b5065120199da/routes/catalog.js#L110) for an example.

2025-01-07 04:56 UTC, h0ethan04 commented on server/routes/event_enrollments.ts
> +    );
We want to be able to update rows individually, see [catalog.js](https://github.com/ctc-uci/aiss-backend/blob/dd6cd70521d990e7cbc027ca905b5065120199da/routes/catalog.js#L110) for an example.

2025-01-07 10:32 UTC, Priyansh4444 commented on server/routes/articles.ts
> +    );
Should we also add the row if it doesn't exist?

2025-01-07 19:29 UTC, h0ethan04 commented on server/routes/articles.ts
> +    );
No we can just update existing ones instead.

2025-01-08 05:18 UTC, stevem-zhou approved these changes
lgtm

2025-01-09 09:03 UTC, h0ethan04 approved these changes

2025-01-10 06:27 UTC, merged