28 create teachers crud routes
ctc-uci/cse pull request #37
Opened 2024-12-29 03:25 UTC by boyuan12

## Description
Implemented 6 backend API calls under `/teachers` route

## Screenshots/Media
**GET /teachers/:id**
![GET /teachers/:id](https://img001.prntscr.com/file/img001/r7f400d1Q_K4fpLr42zpxg.png)

**GET /teachers**
![GET /teachers](https://img001.prntscr.com/file/img001/KA0s8VN8RrGbU67hH6rznA.png)

**GET /teachers/classes/:id**
![GET /teachers/classes/:id](https://img001.prntscr.com/file/img001/KS97e25SRRSSCmbls-aKIg.png)

**POST /teachers**
![POST /teachers](https://img001.prntscr.com/file/img001/aaW5w8onRLmmqpuvSwdTWQ.png)

**PUT /teachers/:id**
![PUT /teachers/:id](https://img001.prntscr.com/file/img001/GtiUoMMlQz-6eT1Qfq1K9Q.png)

**DELETE /teachers/:id**
![DELETE /teachers/:id](https://img001.prntscr.com/file/img001/tJLH9FmfS1i7NSh8OM0OHA.png)

## Issues
Closes #28

2025-01-07 04:13 UTC, h0ethan04 requested changes

2025-01-07 04:13 UTC, h0ethan04 commented on server/routes/teachers.js
> +teachersRouter.get("", async(req, res) => {
For consistency can you change this to use `"/"` instead of an empty endpoint?

2025-01-07 04:13 UTC, h0ethan04 commented on server/routes/teachers.js
> +        const firebaseUid = Math.random().toString(36).slice(2, 7) // TODO: Need to obtain the actual firebaseUid
The firebase UID will be passed in as an argument, can you combine this with the line above?

2025-01-07 04:13 UTC, h0ethan04 commented on server/routes/teachers.js
> +            [experience, isActivated, teacherId]
We want to be able to update individual fields, so that fields are optional. Take a look at [catalog.js](https://github.com/ctc-uci/aiss-backend/blob/main/routes/catalog.js) if you need an example.

2025-01-07 04:13 UTC, h0ethan04 commented on server/routes/teachers.js
> +        )
Making two queries is expensive, combine these two using the Postgres `RETURNING` operator

2025-01-07 04:22 UTC, h0ethan04 requested changes

2025-01-07 04:22 UTC, h0ethan04 commented on server/routes/teachers.js
> +        res.redirect(`/teachers/${teacherId}`)
Use the `RETURNING` operator to get the inserted teacher, and instead of redirecting to the get request set the status to 201 and return the teacher. See [catalog.js](https://github.com/ctc-uci/aiss-backend/blob/dd6cd70521d990e7cbc027ca905b5065120199da/routes/catalog.js#L90) for an example.

2025-01-07 20:04 UTC, h0ethan04 requested changes

2025-01-07 20:04 UTC, h0ethan04 commented on server/routes/teachers.js
> +        console.log(params)
This fails if we only provide the `isActivated` field, you'll need to use parameterization by name instead of by position.

2025-01-08 00:10 UTC, boyuan12 commented on server/routes/teachers.js
> +        console.log(params)
My apologies. It should work now (executed sequentially):

**Initial teacher**
![image](https://github.com/user-attachments/assets/258f84c5-a4f1-4c0e-8573-67277afd038a)

**Updating only `experience`**
![image](https://github.com/user-attachments/assets/085cab70-d628-4874-b13c-35572d4de1e5)

**Updating only `isActivated`**
![image](https://github.com/user-attachments/assets/c7ab8181-21a9-40cd-beb8-281ee08c286b)

**Updating both `experience` and `isActivated`**
![image](https://github.com/user-attachments/assets/2f87fa37-a275-427f-9193-9381f47dca5c)

2025-01-08 09:40 UTC, stevem-zhou commented on server/routes/teachers.js
> +teachersRouter.post("", async(req, res) => {
NIT use "/" here as well instead of a empty quotes

2025-01-08 22:56 UTC, stevem-zhou approved these changes, later dismissed
lgtm

2025-01-09 09:29 UTC, h0ethan04 approved these changes, later dismissed

2025-01-10 06:33 UTC, merged