33 create class enrollments and classes taught crud routes alex
ctc-uci/cse pull request #38
Opened 2024-12-30 22:01 UTC by alexespejo

## Description

## Screenshots/Media

## Issues
Closes #

2025-01-07 04:59 UTC, h0ethan04 requested changes

2025-01-07 04:59 UTC, h0ethan04 commented on server/routes/class_enrollments.js
> +    res.status(200).send({
For posts we use status 201, can you fix that

2025-01-07 04:59 UTC, h0ethan04 commented on server/routes/classes_taught.js
> +    res.status(200).send({
Same as before, use 201 for post

2025-01-07 17:05 UTC, RyPC commented
Thanks, Ethan. I've made those changes.

2025-01-08 23:15 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +import { format } from "mysql";
remove this import since it's not being used

2025-01-08 23:17 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +import { keysToCamel } from "../common/utils";
could we use the keysToCamel function when returning the json, you can take a look at [sample.ts](https://github.com/ctc-uci/Center-Stage/blob/22dea7a8e55a0f834dec5b94a6756fff916b0d8b/server/routes/sample.ts#L15)
we'll update the architecture to follow this

2025-01-08 23:19 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +      `SELECT * FROM class_enrollments WHERE id = ${id};`
could we use sql parameterization here similar to how you're doing it in [line 35](https://github.com/ctc-uci/Center-Stage/blob/43efa681eaa825aa30765a2413dec75a229cad9f/server/routes/class_enrollments.js#L34-L36)

this will prevent SQL injection attacks

2025-01-08 23:20 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +    res.status(200).send(classById);
use `keysToCamel`

2025-01-08 23:20 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +    res.status(200).json(classById);
use `keysToCamel` when returning

2025-01-08 23:25 UTC, stevem-zhou commented on server/routes/class_enrollments.js
> +    });
might be able to just use `keysToCamel` here something like

`res.status(201).json(keysToCamel(result)[0])`

if the above doesn't work you can also just hardcode your returning object params with the camelCase properties:
`studentId`  and `classId`

2025-01-08 23:27 UTC, stevem-zhou commented on server/routes/classes_taught.js
> +    });
same as the `class_enrollments` comment

could use `keysToCamel` here or just replace the properties into their camelCase versions

2025-01-09 00:12 UTC, RyPC commented
Thanks, Steven, I've made those changes. For some reason, I thought the outputs were supposed to be snake_case.

2025-01-09 09:31 UTC, h0ethan04 approved these changes, later dismissed

2025-01-10 06:36 UTC, merged