Created class videos CRUD routes.
ctc-uci/cse pull request #39
Opened 2024-12-31 12:34 UTC by angeliinawang

## Description
Created 5 backend API calls for Class Videos table under /classes-videos route.

## Screenshots/Media
POST /classes-videos/
<img width="887" alt="Screenshot 2024-12-31 at 1 16 44 PM" src="https://github.com/user-attachments/assets/c6c113ce-c6b3-4f18-b8c8-0dd8186f5607" />

PUT /classes-videos/:id
<img width="890" alt="Screenshot 2024-12-31 at 1 19 05 PM" src="https://github.com/user-attachments/assets/19526b6e-7992-49af-9f1f-85031afb9b7c" />

GET /classes-videos/:id
<img width="890" alt="Screenshot 2024-12-31 at 1 19 20 PM" src="https://github.com/user-attachments/assets/02664619-67fd-472e-a4d4-45f8c00eb41f" />

POST /classes-videos/
<img width="892" alt="Screenshot 2024-12-31 at 1 19 56 PM" src="https://github.com/user-attachments/assets/a98ad4b3-d19c-4036-911e-7840a8142a21" />

GET /classes-videos/
<img width="892" alt="Screenshot 2024-12-31 at 1 20 11 PM" src="https://github.com/user-attachments/assets/7e0862e2-4a5d-485d-a19f-acb1257896ee" />

DELETE /classes-videos/:id
<img width="888" alt="Screenshot 2024-12-31 at 1 20 27 PM" src="https://github.com/user-attachments/assets/96ba81f3-1068-42a1-bebd-c4689e3aaa04" />

GET /classes-videos/:id
<img width="888" alt="Screenshot 2024-12-31 at 1 20 38 PM" src="https://github.com/user-attachments/assets/de7813f7-d4a3-4504-860f-a2b05d31e807" />

## Issues
Closes #30

2025-01-07 04:24 UTC, h0ethan04 requested changes

2025-01-07 04:24 UTC, h0ethan04 commented on server/routes/class_videos.js
> +      [title, s3_url, description, media_url, class_id]);
We want to be able to update individual fields in a single request, can you do that? See [catalog.js](https://github.com/ctc-uci/aiss-backend/blob/dd6cd70521d990e7cbc027ca905b5065120199da/routes/catalog.js#L110) for an example.

2025-01-08 23:34 UTC, stevem-zhou commented
looks good, once you guys address Ethan's comment we can approve!

2025-01-08 23:40 UTC, stevem-zhou commented
everything looks good, just address Ethan's comment and we can approve!

2025-01-08 23:44 UTC, stevem-zhou reviewed
everything looks good, just address Ethan's comment and we can approve!

2025-01-09 00:21 UTC, stevem-zhou submitted a review, later dismissed
LGTM

2025-01-09 09:02 UTC, h0ethan04 approved these changes, later dismissed

2025-01-10 06:39 UTC, merged